## Python-SQL coneection

In [1]:
%pip install sqlalchemy ipython-sql

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.40-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Collecting ipython-sql
  Downloading ipython_sql-0.5.0-py3-none-any.whl.metadata (17 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.2-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\teju\adv python\repository\venv\lib\site-packages (from sqlalchemy) (4.13.2)
Collecting prettytable (from ipython-sql)
  Downloading prettytable-3.16.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: ipython in d:\teju\adv python\repository\venv\lib\site-packages (from ipython-sql) (9.1.0)
Collecting sqlparse (from ipython-sql)
  Downloading sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: six in d:\teju\adv python\repository\venv\lib\site-packages (from ipython-sql) (1.17.0)
Collecting ipython-genutils (from ipython-sql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Requirement already satisfied: colorama in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.16 in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack_data in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in d:\teju\adv python\repository\venv\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: wcwidth in d:\teju\adv python\repository\venv\lib\site-packages (from prettytable->ipython-sql) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in d:\teju\adv python\repository\venv\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: executing>=1.2.0 in d:\teju\adv python\repository\venv\lib\site-packages (from stack_data->ipython->ipython-sql) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in d:\teju\adv python\repository\venv\lib\site-packages (from stack_data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in d:\teju\adv python\repository\venv\lib\site-packages (from stack_data->ipython->ipython-sql) (0.2.3)
Downloading sqlalchemy-2.0.40-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 16.3 MB/s eta 0:00:00
Downloading ipython_sql-0.5.0-py3-none-any.whl (20 kB)
Downloading greenlet-3.2.2-cp313-cp313-win_amd64.whl (296 kB)
Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Downloading prettytable-3.16.0-py3-none-any.whl (33 kB)
Downloading sqlparse-0.5.3-py3-none-any.whl (44 kB)
Installing collected packages: ipython-genutils, sqlparse, prettytable, greenlet, sqlalchemy, ipython-sql
Successfully installed greenlet-3.2.2 ipython-genutils-0.2.0 ipython-sql-0.5.0 prettytable-3.16.0 sqlalchemy-2.0.40 sqlparse-0.5.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
%pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.3.0-cp313-cp313-win_amd64.whl.metadata (7.7 kB)
Downloading mysql_connector_python-9.3.0-cp313-cp313-win_amd64.whl (16.4 MB)
   ---------------------------------------- 0.0/16.4 MB ? eta -:--:--
   ----- ---------------------------------- 2.4/16.4 MB 22.4 MB/s eta 0:00:01
   ---------- ----------------------------- 4.5/16.4 MB 14.0 MB/s eta 0:00:01
   ------------- -------------------------- 5.5/16.4 MB 9.8 MB/s eta 0:00:02
   ---------------- ----------------------- 6.6/16.4 MB 8.5 MB/s eta 0:00:02
   ------------------ --------------------- 7.6/16.4 MB 7.7 MB/s eta 0:00:02
   ------------------- -------------------- 7.9/16.4 MB 7.1 MB/s eta 0:00:02
   ------------------- -------------------- 8.1/16.4 MB 6.5 MB/s eta 0:00:02
   -------------------- ------------------- 8.4/16.4 MB 5.8 MB/s eta 0:00:02
   --------------------- ------------------ 8.9/16.4 MB 4.9 MB/s eta 0:00:02
   ---------------------- ----------------- 9.2/16.4 MB 4.7 MB/s eta 0:00:02
   ----------------------- ---------------- 9.7/16.4 MB 4.4 MB/s eta 0:00:02
   ------------------------ --------------- 10.2/16.4 MB 4.2 MB/s eta 0:00:02
   -------------------------- ------------- 10.7/16.4 MB 4.0 MB/s eta 0:00:02
   --------------------------- ------------ 11.3/16.4 MB 4.0 MB/s eta 0:00:02
   ---------------------------- ----------- 11.8/16.4 MB 3.9 MB/s eta 0:00:02
   ------------------------------ --------- 12.6/16.4 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 13.4/16.4 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 14.4/16.4 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 15.2/16.4 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  16.3/16.4 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 16.4/16.4 MB 3.8 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
%pip install PyMySQL

Collecting PyMySQL
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: PyMySQL
Successfully installed PyMySQL-1.1.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Restart the kernel

In [1]:
import pandas as pd

In [2]:
from sqlalchemy import URL,create_engine

In [3]:
conn_str = URL.create(
    drivername="mysql+pymysql",
    username = "root",
    password = "tejaswini1994",
    host = "localhost",
    port = 3306,
    database="tejaswini123"
)

In [4]:
engine = create_engine(conn_str)

## Reading data from mysql database

In [5]:
conn = engine.connect()
# to view all the tables present in tejaswini123
pd.read_sql("show tables",conn)

   Tables_in_tejaswini123
0                athletes
1             course_data
2                 courses
3               customers
4              department
5                    dept
6                dept_123
7                  dept_2
8                  dept_3
9                  drinks
10                   emp3
11                emp_123
12                empdata
13                   empl
14               employee
15                  marks
16                 snacks
17               startups
18                   tips
19                  users
20                 users2

In [9]:
# to extract customers tables information from weekday911 databse
df = pd.read_sql("select * from emp3",conn)
df

   Id       FullName   Salary  ManagerId
0   1     John Smith  10000.0        3.0
1   2  Jane Anderson  12000.0        3.0
2   3      Tom Lanon  15000.0        4.0
3   4    Anne Connor  20000.0        NaN
4   5    Jeremy York   9000.0        1.0

In [ ]:
# to extract FullName,Salary from emp3 table 
df1 = pd.read_sql("select FullName,Salary from emp3",conn)
df1

        FullName   Salary
0     John Smith  10000.0
1  Jane Anderson  12000.0
2      Tom Lanon  15000.0
3    Anne Connor  20000.0
4    Jeremy York   9000.0

## to write/save the tables to mysql databases

In [11]:
# to push the data to mysql database
df1.to_sql("emp3_data_new",conn,if_exists='replace')

5

In [12]:
pd.read_sql("show tables",conn)

   Tables_in_tejaswini123
0                athletes
1             course_data
2                 courses
3               customers
4              department
5                    dept
6                dept_123
7                  dept_2
8                  dept_3
9                  drinks
10                   emp3
11          emp3_data_new
12                emp_123
13                empdata
14                   empl
15               employee
16                  marks
17                 snacks
18               startups
19                   tips
20                  users
21                 users2